# Generated by Django 4.2.5 on 2023-10-21 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flightcountstrategy",
            options={"verbose_name_plural": "Flight Count Strategies"},
        ),
        migrations.AlterModelOptions(
            name="milescountstrategy",
            options={"verbose_name_plural": "Miles Count Strategies"},
        ),
        migrations.AlterModelOptions(
            name="regionalstrategy",
            options={"verbose_name_plural": "Regional Strategies"},
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="flight_count_strategy_id",
            new_name="flight_count_strategy",
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="miles_count_strategy_id",
            new_name="miles_count_strategy",
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="regional_strategy_id",
            new_name="regional_strategy",
        ),
        migrations.RenameField(
            model_name="badgeclaim",
            old_name="user_id",
            new_name="user",
        ),
    ]
