# Generated by Django 4.2.5 on 2023-10-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0003_alter_badge_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="flight_count_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="badges.flightcountstrategy",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="miles_count_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="badges.milescountstrategy",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="regional_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="badges.regionalstrategy",
            ),
        ),
    ]
