import 'package:json_annotation/json_annotation.dart';
import 'package:collection/collection.dart';

enum BlankEnum {
  @JsonValue(null)
  swaggerGeneratedUnknown(null),

  @JsonValue('')
  $null('');

  final String? value;

  const BlankEnum(this.value);
}

enum CountryEnum {
  @JsonValue(null)
  swaggerGeneratedUnknown(null),

  @JsonValue('AF')
  af('AF'),
  @JsonValue('AX')
  ax('AX'),
  @JsonValue('AL')
  al('AL'),
  @JsonValue('DZ')
  dz('DZ'),
  @JsonValue('AS')
  $as('AS'),
  @JsonValue('AD')
  ad('AD'),
  @JsonValue('AO')
  ao('AO'),
  @JsonValue('AI')
  ai('AI'),
  @JsonValue('AQ')
  aq('AQ'),
  @JsonValue('AG')
  ag('AG'),
  @JsonValue('AR')
  ar('AR'),
  @JsonValue('AM')
  am('AM'),
  @JsonValue('AW')
  aw('AW'),
  @JsonValue('AU')
  au('AU'),
  @JsonValue('AT')
  at('AT'),
  @JsonValue('AZ')
  az('AZ'),
  @JsonValue('BS')
  bs('BS'),
  @JsonValue('BH')
  bh('BH'),
  @JsonValue('BD')
  bd('BD'),
  @JsonValue('BB')
  bb('BB'),
  @JsonValue('BY')
  by('BY'),
  @JsonValue('BE')
  be('BE'),
  @JsonValue('BZ')
  bz('BZ'),
  @JsonValue('BJ')
  bj('BJ'),
  @JsonValue('BM')
  bm('BM'),
  @JsonValue('BT')
  bt('BT'),
  @JsonValue('BO')
  bo('BO'),
  @JsonValue('BQ')
  bq('BQ'),
  @JsonValue('BA')
  ba('BA'),
  @JsonValue('BW')
  bw('BW'),
  @JsonValue('BV')
  bv('BV'),
  @JsonValue('BR')
  br('BR'),
  @JsonValue('IO')
  io('IO'),
  @JsonValue('BN')
  bn('BN'),
  @JsonValue('BG')
  bg('BG'),
  @JsonValue('BF')
  bf('BF'),
  @JsonValue('BI')
  bi('BI'),
  @JsonValue('CV')
  cv('CV'),
  @JsonValue('KH')
  kh('KH'),
  @JsonValue('CM')
  cm('CM'),
  @JsonValue('CA')
  ca('CA'),
  @JsonValue('KY')
  ky('KY'),
  @JsonValue('CF')
  cf('CF'),
  @JsonValue('TD')
  td('TD'),
  @JsonValue('CL')
  cl('CL'),
  @JsonValue('CN')
  cn('CN'),
  @JsonValue('CX')
  cx('CX'),
  @JsonValue('CC')
  cc('CC'),
  @JsonValue('CO')
  co('CO'),
  @JsonValue('KM')
  km('KM'),
  @JsonValue('CG')
  cg('CG'),
  @JsonValue('CD')
  cd('CD'),
  @JsonValue('CK')
  ck('CK'),
  @JsonValue('CR')
  cr('CR'),
  @JsonValue('CI')
  ci('CI'),
  @JsonValue('HR')
  hr('HR'),
  @JsonValue('CU')
  cu('CU'),
  @JsonValue('CW')
  cw('CW'),
  @JsonValue('CY')
  cy('CY'),
  @JsonValue('CZ')
  cz('CZ'),
  @JsonValue('DK')
  dk('DK'),
  @JsonValue('DJ')
  dj('DJ'),
  @JsonValue('DM')
  dm('DM'),
  @JsonValue('DO')
  $do('DO'),
  @JsonValue('EC')
  ec('EC'),
  @JsonValue('EG')
  eg('EG'),
  @JsonValue('SV')
  sv('SV'),
  @JsonValue('GQ')
  gq('GQ'),
  @JsonValue('ER')
  er('ER'),
  @JsonValue('EE')
  ee('EE'),
  @JsonValue('SZ')
  sz('SZ'),
  @JsonValue('ET')
  et('ET'),
  @JsonValue('FK')
  fk('FK'),
  @JsonValue('FO')
  fo('FO'),
  @JsonValue('FJ')
  fj('FJ'),
  @JsonValue('FI')
  fi('FI'),
  @JsonValue('FR')
  fr('FR'),
  @JsonValue('GF')
  gf('GF'),
  @JsonValue('PF')
  pf('PF'),
  @JsonValue('TF')
  tf('TF'),
  @JsonValue('GA')
  ga('GA'),
  @JsonValue('GM')
  gm('GM'),
  @JsonValue('GE')
  ge('GE'),
  @JsonValue('DE')
  de('DE'),
  @JsonValue('GH')
  gh('GH'),
  @JsonValue('GI')
  gi('GI'),
  @JsonValue('GR')
  gr('GR'),
  @JsonValue('GL')
  gl('GL'),
  @JsonValue('GD')
  gd('GD'),
  @JsonValue('GP')
  gp('GP'),
  @JsonValue('GU')
  gu('GU'),
  @JsonValue('GT')
  gt('GT'),
  @JsonValue('GG')
  gg('GG'),
  @JsonValue('GN')
  gn('GN'),
  @JsonValue('GW')
  gw('GW'),
  @JsonValue('GY')
  gy('GY'),
  @JsonValue('HT')
  ht('HT'),
  @JsonValue('HM')
  hm('HM'),
  @JsonValue('VA')
  va('VA'),
  @JsonValue('HN')
  hn('HN'),
  @JsonValue('HK')
  hk('HK'),
  @JsonValue('HU')
  hu('HU'),
  @JsonValue('IS')
  $is('IS'),
  @JsonValue('IN')
  $in('IN'),
  @JsonValue('ID')
  id('ID'),
  @JsonValue('IR')
  ir('IR'),
  @JsonValue('IQ')
  iq('IQ'),
  @JsonValue('IE')
  ie('IE'),
  @JsonValue('IM')
  im('IM'),
  @JsonValue('IL')
  il('IL'),
  @JsonValue('IT')
  it('IT'),
  @JsonValue('JM')
  jm('JM'),
  @JsonValue('JP')
  jp('JP'),
  @JsonValue('JE')
  je('JE'),
  @JsonValue('JO')
  jo('JO'),
  @JsonValue('KZ')
  kz('KZ'),
  @JsonValue('KE')
  ke('KE'),
  @JsonValue('KI')
  ki('KI'),
  @JsonValue('KW')
  kw('KW'),
  @JsonValue('KG')
  kg('KG'),
  @JsonValue('LA')
  la('LA'),
  @JsonValue('LV')
  lv('LV'),
  @JsonValue('LB')
  lb('LB'),
  @JsonValue('LS')
  ls('LS'),
  @JsonValue('LR')
  lr('LR'),
  @JsonValue('LY')
  ly('LY'),
  @JsonValue('LI')
  li('LI'),
  @JsonValue('LT')
  lt('LT'),
  @JsonValue('LU')
  lu('LU'),
  @JsonValue('MO')
  mo('MO'),
  @JsonValue('MG')
  mg('MG'),
  @JsonValue('MW')
  mw('MW'),
  @JsonValue('MY')
  my('MY'),
  @JsonValue('MV')
  mv('MV'),
  @JsonValue('ML')
  ml('ML'),
  @JsonValue('MT')
  mt('MT'),
  @JsonValue('MH')
  mh('MH'),
  @JsonValue('MQ')
  mq('MQ'),
  @JsonValue('MR')
  mr('MR'),
  @JsonValue('MU')
  mu('MU'),
  @JsonValue('YT')
  yt('YT'),
  @JsonValue('MX')
  mx('MX'),
  @JsonValue('FM')
  fm('FM'),
  @JsonValue('MD')
  md('MD'),
  @JsonValue('MC')
  mc('MC'),
  @JsonValue('MN')
  mn('MN'),
  @JsonValue('ME')
  me('ME'),
  @JsonValue('MS')
  ms('MS'),
  @JsonValue('MA')
  ma('MA'),
  @JsonValue('MZ')
  mz('MZ'),
  @JsonValue('MM')
  mm('MM'),
  @JsonValue('NA')
  na('NA'),
  @JsonValue('NR')
  nr('NR'),
  @JsonValue('NP')
  np('NP'),
  @JsonValue('NL')
  nl('NL'),
  @JsonValue('NC')
  nc('NC'),
  @JsonValue('NZ')
  nz('NZ'),
  @JsonValue('NI')
  ni('NI'),
  @JsonValue('NE')
  ne('NE'),
  @JsonValue('NG')
  ng('NG'),
  @JsonValue('NU')
  nu('NU'),
  @JsonValue('NF')
  nf('NF'),
  @JsonValue('KP')
  kp('KP'),
  @JsonValue('MK')
  mk('MK'),
  @JsonValue('MP')
  mp('MP'),
  @JsonValue('NO')
  no('NO'),
  @JsonValue('OM')
  om('OM'),
  @JsonValue('PK')
  pk('PK'),
  @JsonValue('PW')
  pw('PW'),
  @JsonValue('PS')
  ps('PS'),
  @JsonValue('PA')
  pa('PA'),
  @JsonValue('PG')
  pg('PG'),
  @JsonValue('PY')
  py('PY'),
  @JsonValue('PE')
  pe('PE'),
  @JsonValue('PH')
  ph('PH'),
  @JsonValue('PN')
  pn('PN'),
  @JsonValue('PL')
  pl('PL'),
  @JsonValue('PT')
  pt('PT'),
  @JsonValue('PR')
  pr('PR'),
  @JsonValue('QA')
  qa('QA'),
  @JsonValue('RE')
  re('RE'),
  @JsonValue('RO')
  ro('RO'),
  @JsonValue('RU')
  ru('RU'),
  @JsonValue('RW')
  rw('RW'),
  @JsonValue('BL')
  bl('BL'),
  @JsonValue('SH')
  sh('SH'),
  @JsonValue('KN')
  kn('KN'),
  @JsonValue('LC')
  lc('LC'),
  @JsonValue('MF')
  mf('MF'),
  @JsonValue('PM')
  pm('PM'),
  @JsonValue('VC')
  vc('VC'),
  @JsonValue('WS')
  ws('WS'),
  @JsonValue('SM')
  sm('SM'),
  @JsonValue('ST')
  st('ST'),
  @JsonValue('SA')
  sa('SA'),
  @JsonValue('SN')
  sn('SN'),
  @JsonValue('RS')
  rs('RS'),
  @JsonValue('SC')
  sc('SC'),
  @JsonValue('SL')
  sl('SL'),
  @JsonValue('SG')
  sg('SG'),
  @JsonValue('SX')
  sx('SX'),
  @JsonValue('SK')
  sk('SK'),
  @JsonValue('SI')
  si('SI'),
  @JsonValue('SB')
  sb('SB'),
  @JsonValue('SO')
  so('SO'),
  @JsonValue('ZA')
  za('ZA'),
  @JsonValue('GS')
  gs('GS'),
  @JsonValue('KR')
  kr('KR'),
  @JsonValue('SS')
  ss('SS'),
  @JsonValue('ES')
  es('ES'),
  @JsonValue('LK')
  lk('LK'),
  @JsonValue('SD')
  sd('SD'),
  @JsonValue('SR')
  sr('SR'),
  @JsonValue('SJ')
  sj('SJ'),
  @JsonValue('SE')
  se('SE'),
  @JsonValue('CH')
  ch('CH'),
  @JsonValue('SY')
  sy('SY'),
  @JsonValue('TW')
  tw('TW'),
  @JsonValue('TJ')
  tj('TJ'),
  @JsonValue('TZ')
  tz('TZ'),
  @JsonValue('TH')
  th('TH'),
  @JsonValue('TL')
  tl('TL'),
  @JsonValue('TG')
  tg('TG'),
  @JsonValue('TK')
  tk('TK'),
  @JsonValue('TO')
  to('TO'),
  @JsonValue('TT')
  tt('TT'),
  @JsonValue('TN')
  tn('TN'),
  @JsonValue('TR')
  tr('TR'),
  @JsonValue('TM')
  tm('TM'),
  @JsonValue('TC')
  tc('TC'),
  @JsonValue('TV')
  tv('TV'),
  @JsonValue('UG')
  ug('UG'),
  @JsonValue('UA')
  ua('UA'),
  @JsonValue('AE')
  ae('AE'),
  @JsonValue('GB')
  gb('GB'),
  @JsonValue('UM')
  um('UM'),
  @JsonValue('US')
  us('US'),
  @JsonValue('UY')
  uy('UY'),
  @JsonValue('UZ')
  uz('UZ'),
  @JsonValue('VU')
  vu('VU'),
  @JsonValue('VE')
  ve('VE'),
  @JsonValue('VN')
  vn('VN'),
  @JsonValue('VG')
  vg('VG'),
  @JsonValue('VI')
  vi('VI'),
  @JsonValue('WF')
  wf('WF'),
  @JsonValue('EH')
  eh('EH'),
  @JsonValue('YE')
  ye('YE'),
  @JsonValue('ZM')
  zm('ZM'),
  @JsonValue('ZW')
  zw('ZW');

  final String? value;

  const CountryEnum(this.value);
}

enum GenderEnum {
  @JsonValue(null)
  swaggerGeneratedUnknown(null),

  @JsonValue('m')
  m('m'),
  @JsonValue('f')
  f('f');

  final String? value;

  const GenderEnum(this.value);
}

enum NullEnum {
  @JsonValue(null)
  swaggerGeneratedUnknown(null),

  @JsonValue('null')
  $null('null');

  final String? value;

  const NullEnum(this.value);
}

enum PassengerTypeEnum {
  @JsonValue(null)
  swaggerGeneratedUnknown(null),

  @JsonValue('ADULT')
  adult('ADULT'),
  @JsonValue('CHILD')
  child('CHILD'),
  @JsonValue('INFANT')
  infant('INFANT');

  final String? value;

  const PassengerTypeEnum(this.value);
}

enum SalutationEnum {
  @JsonValue(null)
  swaggerGeneratedUnknown(null),

  @JsonValue('MR')
  mr('MR'),
  @JsonValue('MS')
  ms('MS'),
  @JsonValue('MRS')
  mrs('MRS'),
  @JsonValue('CHD')
  chd('CHD'),
  @JsonValue('INF')
  inf('INF');

  final String? value;

  const SalutationEnum(this.value);
}
